spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 52.78.44.47

serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 52.78.44.47

serverName: green_server

---


server:
  servlet:
    encoding:
      # 한글깨짐 처리 
      force-response: true

# Spring Data Source 설정 
spring:

  output:
    ansi:
      enabled: always 
  # 데이터 베이스 
  datasource:
    url: jdbc:mysql://fp.c1mucyw28eav.ap-northeast-2.rds.amazonaws.com:3306/fp
    username: fp
    password: qwerasdf1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # sql:
  #   init:
  #     mode: always


  #  데이터 베이스 커넥션 
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
    # defer-datasource-initialization: true
        

  # mustache (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
  mustache:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**


