-- insert into emotion(emotion_type, email, created_date) values('HAPPY','test@g.com', DATE(CONVERT_TZ(NOW(), 'UTC', 'Asia/Seoul')));
-- insert into emotion(emotion_type, email, created_date) values('CALM','test@g.com', DATE(CONVERT_TZ(NOW(), 'UTC', 'Asia/Seoul')));
-- insert into emotion(emotion_type, email, created_date) values('SURPRISE','test@g.com', DATE(CONVERT_TZ(NOW(), 'UTC', 'Asia/Seoul')));
-- insert into emotion(emotion_type, email, created_date) values('SAD','test@g.com', DATE(CONVERT_TZ(NOW(), 'UTC', 'Asia/Seoul')));
-- insert into emotion(emotion_type, email, created_date) values('ANGRY','test@g.com', DATE(CONVERT_TZ(NOW(), 'UTC', 'Asia/Seoul')));